INSERT INTO CUSTOMERS(ID,TITLE_OF_HONOUR, FIRST_NAME, LAST_NAME, IDENTITY_NUMBER) values ( 1, 'MRS','Sonia', 'Wildling','10001');
INSERT INTO CUSTOMERS(ID,TITLE_OF_HONOUR,FIRST_NAME, LAST_NAME, IDENTITY_NUMBER) values ( 2, 'MADAM','Samantha', 'Blade','10002');
INSERT INTO CUSTOMERS(ID,TITLE_OF_HONOUR,FIRST_NAME, LAST_NAME, IDENTITY_NUMBER) values ( 3, 'MR','Danny', 'Khoza','10003');
INSERT INTO CUSTOMERS(ID,TITLE_OF_HONOUR,FIRST_NAME, LAST_NAME, IDENTITY_NUMBER) values ( 4, 'MX','Broke', 'Daniels','10004');

INSERT INTO ACCOUNTS (ID, ACCOUNT_NUMBER,BALANCE, ACCOUNT_TYPE) values ( 1, '04112121', 9641, 'CHEQUE_ACCOUNT');
INSERT INTO ACCOUNTS (ID, ACCOUNT_NUMBER,BALANCE, ACCOUNT_TYPE) values ( 2, '03000121', 4152, 'SAVINGS_ACCOUNT');
INSERT INTO ACCOUNTS (ID, ACCOUNT_NUMBER,BALANCE, ACCOUNT_TYPE) values ( 3, '0500021', -522, 'CREDIT_CARD');
INSERT INTO ACCOUNTS (ID, ACCOUNT_NUMBER,BALANCE, ACCOUNT_TYPE) values ( 4, '0512021', -1722, 'BOND_ACCOUNT');
INSERT INTO ACCOUNTS (ID, ACCOUNT_NUMBER,BALANCE, ACCOUNT_TYPE) values ( 5, '0523021', 10522, 'CHEQUE_ACCOUNT');

INSERT INTO CUSTOMERS_LIST_OF_ACCOUNTS values ( 1,1 );
INSERT INTO CUSTOMERS_LIST_OF_ACCOUNTS values ( 2,2 );
INSERT INTO CUSTOMERS_LIST_OF_ACCOUNTS values ( 3,3 );
INSERT INTO CUSTOMERS_LIST_OF_ACCOUNTS values ( 1,4 );
INSERT INTO CUSTOMERS_LIST_OF_ACCOUNTS values ( 1,5 );